import { StyleSheet, Platform } from 'react-native';

export const getStyles = (isDarkMode: boolean, colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: isDarkMode ? colors.cardBackground : '#FFF',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 15 : 10,
    paddingBottom: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  headerContent: {
    flexDirection: 'column',
    flex: 1,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  headerAvatar: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#1A1A1A',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  headerIconBox: {
    width: 45,
    height: 45,
    borderRadius: 12,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    zIndex: 1000,
  },
  headerGreeting: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.text,
  },
  headerStatus: {
    fontSize: 14,
    color: colors.secondary,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 100,
  },
  mapCard: {
    height: 220,
    borderRadius: 35,
    overflow: 'hidden',
    marginBottom: 25,
    backgroundColor: colors.cardBackground,
    elevation: 5,
  },
  mapImage: {
    width: '100%',
    height: '100%',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 15,
  },
  quickAccessGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 25,
  },
  quickAccessCard: {
    width: '23%',
    backgroundColor: colors.cardBackground,
    borderRadius: 24,
    paddingVertical: 15,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  quickAccessIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickAccessLabel: {
    fontSize: 9,
    textAlign: 'center',
    color: colors.text,
    fontWeight: '700',
  },
  sosWrapper: {
    alignItems: 'center',
    marginVertical: 10,
    marginBottom: 30,
  },
  sosButton: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sosText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
    marginTop: 2,
  },
  occurrenceCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: 25,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  occurrenceIconBox: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  occurrenceTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
  },
  occurrenceDescription: {
    fontSize: 13,
    color: colors.secondary,
  },
  occurrenceTime: {
    fontSize: 11,
    color: colors.secondary,
    marginTop: 4,
  },
  occurrenceInfo: { flex: 1 },
  occurrenceTimeRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  quickAccessIconImage: {
    width: 28,
    height: 28,
  },
  recentSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: colors.cardBackground,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 30 : 15,
    elevation: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconActive: {
    backgroundColor: isDarkMode ? colors.accent : '#FDF2F4',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 18,
    alignItems: 'center',
  },
  navLabel: {
    fontSize: 10,
    color: colors.secondary,
    marginTop: 4,
  },
  navLabelActive: {
    color: colors.primary,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.cardBackground,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  closeButton: {
    padding: 5,
  },
  // Estilos do popup de ativação de localização
  locationPopupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
  },
  locationPopupContent: {
    backgroundColor: colors.cardBackground,
    borderRadius: 30,
    padding: 30,
    alignItems: 'center',
    width: '100%',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  locationPopupIconBox: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  locationPopupTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 12,
    textAlign: 'center',
  },
  locationPopupDescription: {
    fontSize: 15,
    color: colors.secondary,
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 22,
  },
  locationPopupButton: {
    width: '100%',
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  locationPopupButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  locationPopupCancelButton: {
    width: '100%',
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationPopupCancelText: {
    color: colors.secondary,
    fontSize: 15,
    fontWeight: '600',
  },
});