import { Platform, StyleSheet } from 'react-native';

export const getStyles = (isDarkMode: boolean, colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'android' ? 70 : 80,
      paddingBottom: 20,
    },
    backButton: {
      marginRight: 15,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: colors.text,
    },
    headerSubtitle: {
      fontSize: 14,
      color: colors.secondary,
      marginTop: 5,
    },
    tabContainer: {
      flexDirection: 'row',
      backgroundColor: colors.cardBackground,
      marginHorizontal: 20,
      borderRadius: 20,
      padding: 5,
      marginBottom: 20,
    },
    tab: {
      flex: 1,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 15,
    },
    activeTab: {
      backgroundColor: colors.primary,
    },
    tabText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.secondary,
    },
    activeTabText: {
      color: '#FFF',
    },
    filterContainer: {
      paddingHorizontal: 20,
      marginBottom: 15,
    },
    filterLabel: {
      fontSize: 14,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 10,
    },
    chipScroll: {
      flexDirection: 'row',
    },
    filterChip: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: colors.cardBackground,
      marginRight: 10,
      borderWidth: 1,
      borderColor: colors.border,
    },
    activeFilterChip: {
      backgroundColor: isDarkMode ? '#331A1D' : '#FDEEF1',
      borderColor: colors.primary,
    },
    filterChipText: {
      fontSize: 13,
      color: colors.secondary,
    },
    activeFilterChipText: {
      color: colors.primary,
      fontWeight: 'bold',
    },
    actionContainer: {
      paddingHorizontal: 20,
      marginBottom: 18,
    },
    registerButton: {
      height: 50,
      borderRadius: 16,
      backgroundColor: colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      elevation: 5,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    },
    registerButtonText: {
      color: '#FFF',
      fontSize: 15,
      fontWeight: 'bold',
    },
    listContainer: {
      paddingHorizontal: 20,
      paddingBottom: 100,
    },
    occurrenceCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: 25,
      padding: 18,
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 15,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    occurrenceIconBox: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    occurrenceInfo: {
      flex: 1,
    },
    occurrenceTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 12,
    },
    occurrenceTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.text,
      flex: 1,
    },
    occurrenceDescription: {
      fontSize: 13,
      color: colors.secondary,
      marginTop: 2,
    },
    occurrenceTime: {
      fontSize: 11,
      color: colors.secondary,
      marginTop: 6,
    },
    occurrenceDate: {
      fontSize: 11,
      color: colors.secondary,
      marginTop: 2,
    },
    distanceBadge: {
      backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      alignSelf: 'flex-start',
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    distanceText: {
      fontSize: 11,
      fontWeight: 'bold',
      color: colors.primary,
    },
    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 50,
    },
    emptyText: {
      fontSize: 16,
      color: colors.secondary,
      marginTop: 10,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.cardBackground,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 22,
      paddingBottom: Platform.OS === 'ios' ? 34 : 24,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.text,
    },
    modalSubtitle: {
      fontSize: 13,
      color: colors.secondary,
      marginTop: 4,
    },
    closeButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
      alignItems: 'center',
      justifyContent: 'center',
    },
    inputLabel: {
      color: colors.text,
      fontSize: 13,
      fontWeight: 'bold',
      marginBottom: 8,
    },
    typeSelector: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 16,
    },
    typeOption: {
      flex: 1,
      height: 46,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: colors.cardBackground,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    typeOptionActive: {
      backgroundColor: colors.primary,
    },
    typeOptionText: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: 'bold',
    },
    typeOptionTextActive: {
      color: '#FFF',
    },
    input: {
      minHeight: 48,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: isDarkMode ? colors.accent : '#FFF7FA',
      paddingHorizontal: 14,
      color: colors.text,
      fontSize: 14,
      marginBottom: 16,
    },
    textArea: {
      minHeight: 104,
      paddingTop: 14,
    },
    saveButton: {
      height: 52,
      borderRadius: 16,
      backgroundColor: colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    saveButtonDisabled: {
      backgroundColor: '#D8AAB3',
    },
    saveButtonText: {
      color: '#FFF',
      fontSize: 15,
      fontWeight: 'bold',
    },
  });
